# Generated by Django 4.2.11 on 2024-04-28 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0002_famember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='area',
        ),
    ]
