# Generated by Django 4.2.11 on 2024-05-02 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('oauth2_provider', '0007_application_post_logout_redirect_uris'),
        ('apart', '0005_alter_resident_avatar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resident',
            new_name='User',
        ),
    ]
