# Generated by Django 4.2.11 on 2024-05-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0007_rename_user_resident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'unpaid'), ('PAID', 'paid')], default='UNPAID', max_length=10),
        ),
    ]
