# Generated by Django 4.2.11 on 2024-05-04 09:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0009_alter_bill_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='avatar',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
