# Generated by Django 4.2.11 on 2024-05-04 09:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0010_bill_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='avatar',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
