# Generated by Django 4.2.11 on 2024-05-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0011_alter_bill_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='avatar',
        ),
        migrations.AddField(
            model_name='bill',
            name='image',
            field=models.ImageField(default=None, upload_to='images/%Y/%m'),
        ),
    ]
