# Generated by Django 4.2.11 on 2024-05-11 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0012_remove_bill_avatar_bill_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='image',
        ),
        migrations.CreateModel(
            name='SurveyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleanliness_rating', models.PositiveIntegerField()),
                ('facilities_rating', models.PositiveIntegerField()),
                ('services_rating', models.PositiveIntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='apart.survey')),
            ],
        ),
    ]
