# Generated by Django 4.2.11 on 2024-05-11 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0016_alter_resident_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='creator',
        ),
    ]
